### ISSUE TITLE
Standardize documentation using the README

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [10kloud/database#1]
## Current situation
Repository contains binary files and is not documented

## Desired situation
It's a good practice to use the README.md file to explain what's in the repository and avoid saving binary files in git repositories.
My suggestion is:
- [x] Explain the situation on the README file (what is this database for and which data will store)
- [x] Move the images in a dedicated folder and reference them in the README.md
- [x] Delete the pdf and move its content in a section of the README.md file
- [x] Remove the mwb model because you are adding useless dependencies to this project, this means MWB is required to edit the schema. The preferred alternative is a plaintext .sql document with all the necessary instructions.
- [x] Remove the database dump because the repository has to contain the same code that is in production and if you have to edit the database you cannot apply the dump without deleting your data (easily).
- [x] Avoid using spaces in file names

## References
- [Github's markdown guide](https://guides.github.com/features/mastering-markdown/)

**Note**: Create a feature branch from dev, open a pull request against dev and wait for approval

**Comment by BolzanLuca** [comment]
dovrei aver sistemato tutto, manca da creare la tabella dello storico degli allarmi + fare in file sql
